package com.johnsnowlabs.nlp.annotators.assertion.dl

import com.johnsnowlabs.nlp.{Annotation, AnnotatorModel, HasWordEmbeddings, ParamsAndFeaturesWritable}

/**
  * Created by jose on 14/03/18.
  */
class AssertionDLModel extends AnnotatorModel[AssertionDLModel]
  with HasWordEmbeddings
  with ParamsAndFeaturesWritable {
  /**
    * takes a document and annotations and produces new annotations of this annotator's annotation type
    *
    * @param annotations Annotations that correspond to inputAnnotationCols generated by previous annotators if any
    * @return any number of annotations processed for every input annotation. Not necessary one to one relationship
    */
  override protected def annotate(annotations: Seq[Annotation]): Seq[Annotation] = ???

  override val requiredAnnotatorTypes: Array[String] = ???
  override val annotatorType: AnnotatorType = ???
  override val uid: String = ???
}
