version: '3.7'

services:
  spark_nlp_build:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docs/:/docs/
    command: >
      sh -c "jekyll build -I &&
      echo 'Done building' &&
      cp -r /app/_frontend/static _site &&
      touch _site/.nojekyll &&
      echo 'Publishing to Github Pages' &&
      gh-pages -d _site -m 'deploy: ${GIT_COMMIT}' -u '${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>' -t true -r ${GIT_REPO_URL}"
