package com.johnsnowlabs.nlp.annotators.spell.ocr

import com.johnsnowlabs.nlp.{Annotation, AnnotatorModel, AnnotatorType}

class OcrSpellCheckModel(override val uid: String) extends AnnotatorModel[OcrSpellCheckModel]{
  /**
    * takes a document and annotations and produces new annotations of this annotator's annotation type
    *
    * @param annotations Annotations that correspond to inputAnnotationCols generated by previous annotators if any
    * @return any number of annotations processed for every input annotation. Not necessary one to one relationship
    */
  override def annotate(annotations: Seq[Annotation]): Seq[Annotation] = ???

  /** Annotator reference id. Used to identify elements in metadata or to refer to this annotator type */
  override val requiredAnnotatorTypes: Array[String] = Array(AnnotatorType.TOKEN)
  override val annotatorType: AnnotatorType = AnnotatorType.TOKEN
}
