"""Test Modules for the Annotators"""

from test.annotator.embeddings.albert_embeddings_test_spec import *
from test.annotator.classifier_dl.albert_for_token_classification_test_spec import *
from test.annotator.basic_annotator_test_spec import *
from test.annotator.classifier_dl.bert_for_token_classification_test_spec import *
from test.annotator.chunk_doc_serializing_test_spec import *
from test.annotator.embeddings.chunk_embeddings_test_spec import *
from test.annotator.token.chunk_tokenizer_test_spec import *
from test.annotator.chunker_test_spec import *
from test.annotator.classifier_dl.classifier_dl_test_spec import *
from test.annotator.spell_check.context_spell_checker_model_test_spec import *
from test.annotator.matcher.date_matcher_test_spec import *
from test.annotator.classifier_dl.deberta_for_sequence_classification_test_spec import *
from test.annotator.classifier_dl.distil_bert_for_sequence_classification_test_spec import *
from test.annotator.embeddings.doc2_vec_test_spec import *
from test.annotator.document_normalizer_spec import *
from test.annotator.embeddings.elmo_embeddings_test_spec import *
from test.annotator.embeddings.embeddings_finisher_test_spec import *
from test.annotator.er.entity_ruler_test_spec import *
from test.annotator.get_classes_test_spec import *
from test.annotator.seq2seq.gpt2_transformer_text_generation_test_spec import *
from test.annotator.graph_extraction_test_spec import *
from test.annotator.ld_dl.language_detector_dl_test_spec import *
from test.annotator.lemmatizer_test_spec import *
from test.annotator.classifier_dl.longformer_for_token_classification_test_spec import *
from test.annotator.classifier_dl.multi_classifier_dl_test_spec import *
from test.annotator.n_gram_generator_test_spec import *
from test.annotator.ner.ner_dl_model_test_spec import *
from test.annotator.normalizer_test_spec import *
from test.annotator.spell_check.norvig_sweeting_model_test_spec import *
from test.annotator.params_getters_test_spec import *
from test.annotator.pos.perceptron_test_spec import *
from test.annotator.pipeline_test_spec import *
from test.annotator.sentence.pragmatic_test_spec import *
from test.annotator.matcher.regex_matcher_test_spec import *
from test.annotator.token.regex_tokenizer_test_spec import *
from test.annotator.classifier_dl.roberta_for_sequence_classification_test_spec import *
from test.annotator.classifier_dl.roberta_for_token_classification_test_spec import *
from test.annotator.embeddings.roberta_sentence_embeddings_test_spec import *
from test.annotator.sentence.sentence_detector_dl_test_spec import *
from test.annotator.embeddings.sentence_embeddings_test_spec import *
from test.annotator.sentiment.sentiment_dl_test_spec import *
from test.annotator.spell_check.spell_checker_test_spec import *
from test.annotator.stop_words_cleaner_test_spec import *
from test.annotator.spell_check.symmetric_delete_test_spec import *
from test.annotator.seq2seq.t5_transformer_test_spec import *
from test.annotator.matcher.text_matcher_test_spec import *
from test.annotator.token.tokenizer_test_spec import *
from test.annotator.embeddings.universal_sentence_encoder_test_spec import *
from test.annotator.embeddings.word2_vec_test_spec import *
from test.annotator.ws.word_segmenter_test_spec import *
from test.annotator.classifier_dl.xlm_roberta_for_sequence_classification_test_spec import *
from test.annotator.classifier_dl.xlm_roberta_for_token_classification_test_spec import *
from test.annotator.embeddings.xlnet_embeddings_test_spec import *
from test.annotator.classifier_dl.xlnet_for_token_classification_test_spec import *
from test.annotator.keyword_extraction.yake_keyword_extraction_test_spec import *
from test.annotator.dependency.dependency_parser_test_spec import *
from test.annotator.dependency.typed_dependency_parser_test_spec import *
