/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI */

#ifndef _Included_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
#define _Included_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppCtor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppCtor
  (JNIEnv *, jclass);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppDtor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppDtor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppLoad
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppLoad
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppLoadOrDie
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppLoadOrDie
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppLoadFromSerializedProto
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppLoadFromSerializedProto
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppSetEncodeExtraOptions
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppSetEncodeExtraOptions
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppSetDecodeExtraOptions
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppSetDecodeExtraOptions
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppSetVocabulary
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppSetVocabulary
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppResetVocabulary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppResetVocabulary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppLoadVocabulary
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppLoadVocabulary
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppEncodeAsPieces
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppEncodeAsPieces
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppEncodeAsIds
 * Signature: (JLjava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppEncodeAsIds
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppDecodePieces
 * Signature: (J[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppDecodePieces
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppDecodeIds
 * Signature: (J[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppDecodeIds
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppNBestEncodeAsPieces
 * Signature: (JLjava/lang/String;I)[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppNBestEncodeAsPieces
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppNBestEncodeAsIds
 * Signature: (JLjava/lang/String;I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppNBestEncodeAsIds
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppSampleEncodeAsPieces
 * Signature: (JLjava/lang/String;IF)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppSampleEncodeAsPieces
  (JNIEnv *, jclass, jlong, jstring, jint, jfloat);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppSampleEncodeAsIds
 * Signature: (JLjava/lang/String;IF)[I
 */
JNIEXPORT jintArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppSampleEncodeAsIds
  (JNIEnv *, jclass, jlong, jstring, jint, jfloat);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppEncodeAsSerializedProto
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppEncodeAsSerializedProto
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppSampleEncodeAsSerializedProto
 * Signature: (JLjava/lang/String;IF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppSampleEncodeAsSerializedProto
  (JNIEnv *, jclass, jlong, jstring, jint, jfloat);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppNBestEncodeAsSerializedProto
 * Signature: (JLjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppNBestEncodeAsSerializedProto
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppDecodePiecesAsSerializedProto
 * Signature: (J[Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppDecodePiecesAsSerializedProto
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppDecodeIdsAsSerializedProto
 * Signature: (J[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppDecodeIdsAsSerializedProto
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppGetPieceSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppGetPieceSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppPieceToId
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppPieceToId
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppIdToPiece
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppIdToPiece
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppGetScore
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppGetScore
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppIsUnknown
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppIsUnknown
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppIsControl
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppIsControl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppIsUnused
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppIsUnused
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppUnkId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppUnkId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppBosId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppBosId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppEosId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppEosId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI
 * Method:    sppPadId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_johnsnowlabs_nlp_sentencepiece_SentencePieceJNI_sppPadId
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
