package:
  name: "spark-nlp"
  version: 3.1.2

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-3.1.2.tar.gz
    url: https://files.pythonhosted.org/packages/9c/4b/09c38ed05e0c5fcb6cd473a60358fa320b2d16f81a7fd30b5784f9bc582c/spark-nlp-3.1.2.tar.gz
    sha256: a0cf9541f7d3c54546c535600fc9d8c14a4d08e5eea59c81f9ec312176803a0c
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
