package:
  name: "spark-nlp"
  version: 3.0.0

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-3.0.0.tar.gz
    url: https://files.pythonhosted.org/packages/59/73/0855e7cc00821348b3b3f73142a37235c7dd30ba4488ee7c296ebb9f1e5a/spark-nlp-3.0.0.tar.gz
    sha256: d527397ac89cfa262ed5ca51fa077af1f16b60db1fd6fb2c237d4a49debab9ea
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
