package:
  name: "spark-nlp"
  version: 4.2.4

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-4.2.4.tar.gz
    url: https://files.pythonhosted.org/packages/b1/ab/349d8f0ecbf431046470827c065d0a045d113d6dae166a1b6c576b0ad21b/spark-nlp-4.2.4.tar.gz
    sha256: 1093f7a9d184ab0a02cce75874e0c8e853810ba06e49d4404f1a240c00a5fef1
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
