/*
 * Copyright 2017-2026 John Snow Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.johnsnowlabs.nlp.annotators

import com.johnsnowlabs.nlp.functions.ExplodeAnnotations
import com.johnsnowlabs.nlp.{Annotation, AnnotatorModel, AnnotatorType, HasSimpleAnnotate}
import com.johnsnowlabs.partition.{TitleChunkSection, TitleChunker}
import com.johnsnowlabs.reader.ElementType
import org.apache.spark.ml.param.{BooleanParam, IntParam, Param}
import org.apache.spark.ml.util.{DefaultParamsReadable, Identifiable}
import org.apache.spark.sql.DataFrame

/** Annotator that groups element-level documents into title-aware sections.
  *
  * `DocumentTitleSplitter` is intended to work with element-level `DOCUMENT` annotations, such as
  * those generated by `Reader2Doc().setOutputAsDocument(false)`. Whenever a `Title` element is
  * encountered in the input metadata, it starts a new semantic section and the title is kept with
  * the following content.
  *
  * If overflow splitting is enabled, sections larger than `maxCharacters` are further split into
  * smaller documents. Otherwise, each semantic section is emitted as a single chunk regardless of
  * length.
  */
class DocumentTitleSplitter(override val uid: String)
    extends AnnotatorModel[DocumentTitleSplitter]
    with HasSimpleAnnotate[DocumentTitleSplitter] {

  def this() = this(Identifiable.randomUID("DocumentTitleSplitter"))

  override val inputAnnotatorTypes: Array[AnnotatorType] = Array(AnnotatorType.DOCUMENT)
  override val outputAnnotatorType: AnnotatorType = AnnotatorType.DOCUMENT

  /** String used to join element texts inside a section (Default: `" "`)
    *
    * @group param
    */
  val joinString: Param[String] =
    new Param[String](this, "joinString", "String used to join element texts inside a section")

  /** @group setParam */
  def setJoinString(value: String): this.type = {
    require(value != null, "Join string cannot be null.")
    set(joinString, value)
  }

  /** @group getParam */
  def getJoinString: String = $(joinString)

  /** Whether to start a new section when the page number changes (Default: `false`)
    *
    * @group param
    */
  val splitOnPageChange: BooleanParam = new BooleanParam(
    this,
    "splitOnPageChange",
    "Whether to start a new section when the page number changes")

  /** @group setParam */
  def setSplitOnPageChange(value: Boolean): this.type = set(splitOnPageChange, value)

  /** @group getParam */
  def getSplitOnPageChange: Boolean = $(splitOnPageChange)

  /** Whether to split oversized sections after title-based grouping (Default: `false`)
    *
    * @group param
    */
  val enableOverflowSplitting: BooleanParam = new BooleanParam(
    this,
    "enableOverflowSplitting",
    "Whether to split oversized sections after title-based grouping")

  /** @group setParam */
  def setEnableOverflowSplitting(value: Boolean): this.type = set(enableOverflowSplitting, value)

  /** @group getParam */
  def getEnableOverflowSplitting: Boolean = $(enableOverflowSplitting)

  /** Maximum size of an overflow-split chunk (Default: `500`)
    *
    * @group param
    */
  val maxCharacters: IntParam =
    new IntParam(this, "maxCharacters", "Maximum size of an overflow-split chunk")

  /** @group setParam */
  def setMaxCharacters(value: Int): this.type = {
    require(value > 0, "maxCharacters should be larger than 0.")
    set(maxCharacters, value)
  }

  /** @group getParam */
  def getMaxCharacters: Int = $(maxCharacters)

  /** Whether to explode split chunks to separate rows (Default: `false`)
    *
    * @group param
    */
  val explodeSplits: BooleanParam =
    new BooleanParam(this, "explodeSplits", "Whether to explode split chunks to separate rows")

  /** @group setParam */
  def setExplodeSplits(value: Boolean): this.type = set(explodeSplits, value)

  /** @group getParam */
  def getExplodeSplits: Boolean = $(explodeSplits)

  setDefault(
    joinString -> " ",
    splitOnPageChange -> false,
    enableOverflowSplitting -> false,
    maxCharacters -> 500,
    explodeSplits -> false)

  override def annotate(annotations: Seq[Annotation]): Seq[Annotation] = {
    val chunkedSections = TitleChunker.chunkAnnotationsByTitle(
      annotations = annotations,
      joinString = getJoinString,
      splitOnPageChange = getSplitOnPageChange,
      enableOverflowSplitting = getEnableOverflowSplitting,
      maxCharacters = getMaxCharacters)

    var currentOffset = 0

    chunkedSections.zipWithIndex.flatMap { case (section, index) =>
      val text = section.text.trim
      if (text.isEmpty) {
        None
      } else {
        val begin = currentOffset
        val end = begin + text.length - 1
        currentOffset = end + 1

        Some(
          Annotation(
            annotatorType = AnnotatorType.DOCUMENT,
            begin = begin,
            end = end,
            result = text,
            metadata = buildMetadata(section, index),
            embeddings = Array.emptyFloatArray))
      }
    }
  }

  override protected def afterAnnotate(dataset: DataFrame): DataFrame = {
    if (getExplodeSplits) dataset.explodeAnnotationsCol(getOutputCol, getOutputCol) else dataset
  }

  private def buildMetadata(
      section: TitleChunkSection[Annotation],
      index: Int): Map[String, String] = {
    val sectionTitle = section.items
      .collectFirst {
        case item if item.elementType.exists(_.equalsIgnoreCase(ElementType.TITLE)) =>
          item.text.trim
      }
      .filter(_.nonEmpty)

    val commonMetadata = getCommonMetadata(section.items.map(_.metadata))

    commonMetadata -- Set("elementType", "sentence", "document") ++
      Map("document" -> index.toString) ++
      sectionTitle.map("sectionTitle" -> _)
  }

  private def getCommonMetadata(metadataItems: Seq[Map[String, String]]): Map[String, String] = {
    if (metadataItems.isEmpty) {
      Map.empty
    } else {
      val commonKeys = metadataItems.map(_.keySet).reduce(_ intersect _)
      commonKeys.flatMap { key =>
        val values = metadataItems.flatMap(_.get(key)).distinct
        if (values.length == 1) Some(key -> values.head) else None
      }.toMap
    }
  }
}

object DocumentTitleSplitter extends DefaultParamsReadable[DocumentTitleSplitter]
