/*
 * Copyright 2017-2025 John Snow Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.johnsnowlabs.partition

import com.johnsnowlabs.nlp.AnnotatorType.{CHUNK, DOCUMENT}
import com.johnsnowlabs.nlp.{Annotation, AnnotatorModel, HasSimpleAnnotate}
import com.johnsnowlabs.reader.{HTMLElement, TextReader}
import org.apache.spark.ml.PipelineModel
import org.apache.spark.ml.param.Param
import org.apache.spark.ml.util.Identifiable
import org.apache.spark.sql.functions.{col, udf}
import org.apache.spark.sql.types.{ArrayType, StructType}
import org.apache.spark.sql.{DataFrame, Dataset, Encoders, Row}
import org.apache.spark.sql.functions.explode
import org.slf4j.{Logger, LoggerFactory}

class PartitionTransformer(override val uid: String)
    extends AnnotatorModel[PartitionTransformer]
    with HasSimpleAnnotate[PartitionTransformer] {

  def this() = this(Identifiable.randomUID("PartitionTransformer"))
  protected val logger: Logger = LoggerFactory.getLogger(getClass.getName)

  /** Annotator reference id. Used to identify elements in metadata or to refer to this annotator
    * type
    */
  override val inputAnnotatorTypes: Array[AnnotatorType] = Array(DOCUMENT)
  override val outputAnnotatorType: AnnotatorType = DOCUMENT

  override def setInputCols(value: Array[String]): this.type = {
    val validAnnotatorTypes = Array(DOCUMENT, CHUNK)
    require(
      value.length == inputAnnotatorTypes.length,
      s"setInputCols in ${this.uid} expecting ${inputAnnotatorTypes.length} columns. " +
        s"Provided column amount: ${value.length}. " +
        s"Which should be columns from one of the following annotators: ${validAnnotatorTypes.mkString(", ")} ")
    set(inputCols, value)
  }

  val contentPath = new Param[String](this, "contentPath", "Path to the content source")

  def setContentPath(value: String): this.type = set(contentPath, value)

  setDefault(contentPath, "")

  /** takes a document and annotations and produces new annotations of this annotator's annotation
    * type
    *
    * @param annotations
    *   Annotations that correspond to inputAnnotationCols generated by previous annotators if any
    * @return
    *   any number of annotations processed for every input annotation. Not necessary one to one
    *   relationship
    */
  override def annotate(annotations: Seq[Annotation]): Seq[Annotation] = {
    annotations
  }

  override def _transform(
      dataset: Dataset[_],
      recursivePipeline: Option[PipelineModel]): DataFrame = {
    val partitionDf = if ($(contentPath).isEmpty) {
      val textReader = new TextReader()
      val textColum = if (get(inputCols).isDefined) {
        $(inputCols).head
      } else {
        textReader.getOutputColumn
      }
      val flattenDf = dataset.withColumn("flatten_result", explode(col(s"$textColum.result")))
      textReader.setOutputColumn(textColum)
      val parseTxtUDF = udf((text: String) => textReader.parseTxt(text))
      flattenDf.withColumn(textColum, parseTxtUDF(col("flatten_result"))).drop("flatten_result")
    } else {
      if (get(inputCols).isDefined) {
        Partition().setOutputColumn($(inputCols).head).partition($(contentPath))
      } else Partition().partition($(contentPath))

    }
    val colName = findHTMLElementColumn(partitionDf).getOrElse {
      val schemaString = partitionDf.schema.treeString
      throw new IllegalArgumentException(
        s"""❌ No column of type Array[HTMLElement] was found in the DataFrame.
           |
           |💡 Expected a column with schema matching: Array[HTMLElement]
           |
           |🧪 DataFrame Schema:
           |$schemaString
           |
           |👉 Make sure at least one column is an Array of structs with fields:
           |  - elementType: String
           |  - content: String
           |  - metadata: Map[String, String]
     """.stripMargin)
    }
    partitionDf.withColumn(getOutputCol, wrapColumnMetadata(convertToAnnotations(col(colName))))
  }

  private def convertToAnnotations = udf { elements: Seq[Row] =>
    elements.map { row =>
      val content = row.getAs[String]("content")
      val metadata = row.getAs[Map[String, String]]("metadata")

      val begin = 0
      val end = if (content != null) content.length - 1 else 0

      Annotation(
        annotatorType = DOCUMENT,
        begin = begin,
        end = end,
        result = content,
        metadata = metadata,
        embeddings = Array.emptyFloatArray)
    }
  }

  private def findHTMLElementColumn(df: org.apache.spark.sql.DataFrame): Option[String] = {
    val htmlElementSchema = Encoders.product[HTMLElement].schema
    df.schema.fields
      .find { field =>
        field.dataType match {
          case ArrayType(structType: StructType, _) =>
            structType == htmlElementSchema
          case _ => false
        }
      }
      .map(_.name)
  }

}
