package com.jsl.nlp.annotators.sda.vivekn

import com.jsl.nlp.annotators.common.IntStringMapParam
import com.jsl.nlp.util.ConfigHelper
import com.jsl.nlp.{Annotation, AnnotatorModel}
import com.typesafe.config.Config
import org.apache.spark.ml.param.{IntParam, StringArrayParam}
import org.apache.spark.ml.util.{DefaultParamsReadable, Identifiable}

class ViveknSentimentModel(override val uid: String) extends AnnotatorModel[ViveknSentimentModel] {

  import com.jsl.nlp.AnnotatorType._

  private val config: Config = ConfigHelper.retrieve
  private val importantFeatureRatio = config.getDouble("nlp.viveknSentiment.importantFeaturesRatio")
  private val unimportantFeatureStep = config.getDouble("nlp.viveknSentiment.unimportantFeaturesStepRatio")
  private val featureLimit = config.getInt("nlp.viveknSentiment.featuresLimit")

  override val annotatorType: AnnotatorType = SENTIMENT

  override val requiredAnnotatorTypes: Array[AnnotatorType] = Array(TOKEN, DOCUMENT)

  protected val positive: IntStringMapParam = new IntStringMapParam(this, "positive_sentences", "positive sentences trained")
  protected val negative: IntStringMapParam = new IntStringMapParam(this, "negative_sentences", "negative sentences trained")
  protected val features: StringArrayParam = new StringArrayParam(this, "words", "unique words trained")
  protected val positiveTotals: IntParam = new IntParam(this, "positive_totals", "count of positive words")
  protected val negativeTotals: IntParam = new IntParam(this, "negative_totals", "count of negative words")

  def this() = this(Identifiable.randomUID("VIVEKN"))

  private[vivekn] def setPositive(value: Map[String, Int]) = set(positive, value)
  private[vivekn] def setNegative(value: Map[String, Int]) = set(negative, value)
  private[vivekn] def setPositiveTotals(value: Int) = set(positiveTotals, value)
  private[vivekn] def setNegativeTotals(value: Int) = set(negativeTotals, value)
  private[vivekn] def setWords(value: Array[String]) = {
    require(value.nonEmpty, "Word analysis for features cannot be empty. Set prune to false if training is small")
    val currentFeatures = scala.collection.mutable.Set.empty[String]
    val start = (value.length * importantFeatureRatio).ceil.toInt
    val afterStart = {
      if (featureLimit == -1) value.length
      else featureLimit
    }
    val step = (afterStart * unimportantFeatureStep).ceil.toInt
    value.take(start).foreach(currentFeatures.add)
    Range(start, afterStart, step).foreach(k => {
      value.slice(k, k+step).foreach(currentFeatures.add)
    })
    set(features, currentFeatures.toArray)
  }

  def classify(sentence: List[String]): Boolean = {
    val words = ViveknSentimentApproach.negateSequence(sentence).intersect($(features)).distinct
    if (words.isEmpty) return true
    val positiveProbability = words.map(word => scala.math.log(($(positive).getOrElse(word, 0) + 1.0) / (2.0 * $(positiveTotals)))).sum
    val negativeProbability = words.map(word => scala.math.log(($(negative).getOrElse(word, 0) + 1.0) / (2.0 * $(negativeTotals)))).sum
    positiveProbability > negativeProbability
  }

  /**
    * Tokens are needed to identify each word in a sentence boundary
    * POS tags are optionally submitted to the model in case they are needed
    * Lemmas are another optional annotator for some models
    * Bounds of sentiment are hardcoded to 0 as they render useless
    * @param annotations Annotations that correspond to inputAnnotationCols generated by previous annotators if any
    * @return any number of annotations processed for every input annotation. Not necessary one to one relationship
    */
  override def annotate(annotations: Seq[Annotation]): Seq[Annotation] = {
    val sentences = annotations
      .filter(_.annotatorType == DOCUMENT)
    val tokens = annotations
      .filter(_.annotatorType == TOKEN)
    sentences.map(sentence => {
      Annotation(
        annotatorType,
        0,
        0,
        Map(annotatorType -> {
          val targetTokens = tokens
            .filter(token => token.begin >= sentence.begin && token.end <= sentence.end)
            .flatMap(_.metadata.values)
            .toList
          if (classify(targetTokens)) "positive" else "negative"
        })
      )
    })
  }

}
object ViveknSentimentModel extends DefaultParamsReadable[ViveknSentimentModel]