package com.johnsnowlabs.nlp.annotators.similarity

import com.johnsnowlabs.nlp.AnnotatorType.{DOC_SIMILARITY_RANKINGS, SENTENCE_EMBEDDINGS}
import com.johnsnowlabs.nlp.embeddings.HasEmbeddingsProperties
import com.johnsnowlabs.nlp.serialization.MapFeature
import com.johnsnowlabs.nlp.{Annotation, AnnotatorModel, HasSimpleAnnotate, ParamsAndFeaturesWritable}
import com.johnsnowlabs.storage.HasStorageRef
import org.apache.spark.ml.util.{DefaultParamsReadable, Identifiable}
import org.apache.spark.sql.functions.col

import scala.util.hashing.MurmurHash3

class DocumentSimilarityRankerModel(override val uid: String)
  extends AnnotatorModel[DocumentSimilarityRankerModel]
    with HasSimpleAnnotate[DocumentSimilarityRankerModel]
    with HasStorageRef
    with HasEmbeddingsProperties
    with ParamsAndFeaturesWritable {

  override val inputAnnotatorTypes: Array[AnnotatorType] = Array(SENTENCE_EMBEDDINGS)

  override val outputAnnotatorType: AnnotatorType = DOC_SIMILARITY_RANKINGS

  def this() = this(Identifiable.randomUID("DOC_SIMILARITY_RANKER"))

  /** Dictionary of words with their vectors
   *
   * @group param
   */
  val similarityMappings: MapFeature[String, Map[Int, Array[Int]]] = new MapFeature(this, "similarityMappings")

  /** @group setParam */
  def setSimilarityMappings(value: Map[String, Map[Int, Array[Int]]]): this.type = set(similarityMappings, value)

  def getSimilarityMappings: Map[Int, Array[Int]] = $$(similarityMappings).getOrElse("similarityMappings", Map.empty)

  setDefault(
    inputCols -> Array(SENTENCE_EMBEDDINGS),
    outputCol -> DOC_SIMILARITY_RANKINGS
  )

  /** takes a document and annotations and produces new annotations of this annotator's annotation
   * type
   *
   * @param annotations
   * Annotations that correspond to inputAnnotationCols generated by previous annotators if any
   * @return
   * any number of annotations processed for every input annotation. Not necessary one to one
   * relationship
   */
  override def annotate(annotations: Seq[Annotation]): Seq[Annotation] =

    annotations.map(
      annotation => {
        val inputResult = annotation.result
        val targetIndex = MurmurHash3.stringHash(inputResult, MurmurHash3.stringSeed)
        val neighbors: Array[Int] = getSimilarityMappings.getOrElse(targetIndex, Array(-1)) // index NA

        Annotation(
          annotatorType = outputAnnotatorType,
          begin = annotation.begin,
          end = annotation.end,
          result = annotation.result,
          metadata = annotation.metadata
            + ("lshId"-> targetIndex.toString)
            + ("lshNeighbors" -> neighbors.mkString("[", ",", "]")) ,
          embeddings = annotation.embeddings)
      }
    )
}

object DocumentSimilarityRanker extends DefaultParamsReadable[DocumentSimilarityRankerModel]