name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: yarn run test-all
      - name: Upload coverage to Codecov
        uses: ./
        with:
          files: ./coverage/calculator/coverage-final.json,./coverage/index/coverage-final.json
          file: ./coverage/coverage-final.json
          flags: unittest
          name: codecov-1
      - name: Upload coverage to Codecov (verbose)
        uses: ./
        with:
          files: ./coverage/calculator/coverage-final.json,./coverage/index/coverage-final.json
          file: ./coverage/coverage-final.json
          flags: unittest
          name: codecov-1
          verbose: true